### ISSUE TITLE
hcaptcha resolution problem with the extension

### ISSUE THREAD

**Issue by diegoooooooooooooooo** [capsolver/capsolver-browser-extension#1]
the hcaptcha of the type below are not resolved, he presses directly on skip, which causes non-resolution of this one.
I am using version 0.0.3

![image](https://github.com/capsolver/capsolver-browser-extension/assets/38768160/c840d062-77a4-4672-a8a1-a4ca36856798)

**Comment by capsolver** [comment]
we will fix next version

**Comment by diegoooooooooooooooo** [comment]
thanks
